### ISSUE TITLE
PiPy packages for Python 2

### ISSUE THREAD

**Issue by BoboTiG** [pywin32/pypiwin32#67]
Hello,

Since version `220`, there are no more packages for Python < 3.6.
219: https://pypi.python.org/pypi/pypiwin32/219
220: https://pypi.python.org/pypi/pypiwin32/220

But I checked commits between those 2 releases and did not find something saying you dropped its support. Is it a temporary issue?

**Comment by xoviat** [comment]
There will be no more packages uploaded for Python 2 on pypi (I believe that you can download them from sourceforge).  There will be newer packages uploaded for Python > 3.4, but those will the win32core, win32gui, and win32compat packages. 

You can download the newer packages for Python 2.7 from sourceforge. However, I strongly suspect that the Python 2.7 packages will never be updated because Python 2.7 is being phased out and windows doesn't have OS python dependencies that are three years old.

**Comment by BoboTiG** [comment]
OK, thank you for the quick answer.
